//
// Created by steve on 18-1-24.
//

#ifndef ALGORITHMWORKFLOWTOOLS_THREADSAFEOSTREAM_H
#define ALGORITHMWORKFLOWTOOLS_THREADSAFEOSTREAM_H


class ThreadSafeOStream {

};


#endif //ALGORITHMWORKFLOWTOOLS_THREADSAFEOSTREAM_H
